/**
 * Entry point for @nemo/angular.
 *
 * `./lib/stencil-generated/` is generated by the `angularOutputTarget` in
 * ../components/stencil.config.ts when you run `npm run build` (or
 * `npm run build -w @nemo/components`) from the repo root. It does not exist
 * until that build has run at least once — see README.md.
 */
export * from './lib/nemo-components.module';
export { DIRECTIVES } from './lib/stencil-generated';
export * from './lib/stencil-generated/components';
