/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NemoButtonSize, NemoButtonType, NemoButtonVariant } from "./components/button/button";
import { NemoIconName } from "./components/icon/icons.generated";
import { NemoValidationState } from "./components/text-input/text-input";
export { NemoButtonSize, NemoButtonType, NemoButtonVariant } from "./components/button/button";
export { NemoIconName } from "./components/icon/icons.generated";
export { NemoValidationState } from "./components/text-input/text-input";
export namespace Components {
    /**
     * Nemo button. Maps the Figma `Type` (Primary/Secondary/Tertiary/Small/Icon) and
     * `State` (Default/Hover/Disabled) onto a clean orthogonal API: variant + size are
     * props; hover/focus/pressed are CSS states.
     * Styling references the **semantic** color tier only (`--nemo-color-*`). Spacing,
     * radius, typography and elevation use the resolved Figma values directly until those
     * foundations get their own token tiers (future, additive).
     */
    interface NemoButton {
        /**
          * Accessible name — used as `aria-label`, required for icon-only buttons.
         */
        "accessibleLabel"?: string;
        /**
          * Disabled. Reflected to the host and the native button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Stretch to the full width of the container.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Icon-only button (32×32). Requires `accessibleLabel` for an accessible name.
          * @default false
         */
        "iconOnly": boolean;
        /**
          * Loading: shows a spinner, preserves width, sets `aria-busy`, and is non-interactive.
          * @default false
         */
        "loading": boolean;
        /**
          * Size. `medium` ≈ 37px tall, `small` ≈ 25px tall (per Figma).
          * @default 'medium'
         */
        "size": NemoButtonSize;
        /**
          * Native button type.
          * @default 'button'
         */
        "type": NemoButtonType;
        /**
          * Visual emphasis.
          * @default 'primary'
         */
        "variant": NemoButtonVariant;
    }
    /**
     * Nemo icon — renders one icon from the design system's optimized set
     * (source SVGs in `packages/components/icons/`, optimized via SVGO into the
     * generated `icons.generated.ts` registry by `npm run icons:build`).
     * Tokenized by design: every icon strokes in `currentColor`, so it inherits
     * whatever color its context already has (a button's label color, a text
     * input's icon color, plain text) — there is no per-icon color prop and no
     * hex anywhere in this component.
     * Accessibility: an icon is treated as **decorative** by default
     * (`aria-hidden="true"`) because it almost always sits next to text or
     * inside a labelled control (e.g. `nemo-button`'s `accessible-label`). Pass
     * `label` only when the icon is the *sole* accessible content — this
     * switches it to `role="img"` + `aria-label` instead.
     */
    interface NemoIcon {
        /**
          * Accessible name. Omit for a decorative icon that's already described by its context (the common case — e.g. inside `nemo-button`).
         */
        "label"?: string;
        /**
          * Icon name — must match a key generated from `icons/*.svg`.
         */
        "name": NemoIconName;
        /**
          * Pixel size (square). Defaults to 24, matching every source icon's viewBox.
          * @default 24
         */
        "size": number;
    }
    /**
     * Nemo text input. Implements the Figma text-field (node 4-33): a notched-outline
     * field with a persistent label, helper text, and error/warning validation.
     * Runtime/CSS states (Default/Hover/Active/Filled) are handled with `:hover` /
     * `:focus-within` / a populated value. Disabled, Read only, Error and Warning are props.
     * **Read-only is a distinct, focusable, announced state — never implemented as disabled.**
     * Colors reference the semantic token tier only (`--nemo-color-*`).
     */
    interface NemoTextInput {
        /**
          * Disabled (non-focusable, non-editable). Use sparingly — prefer read-only for display.
          * @default false
         */
        "disabled": boolean;
        /**
          * Render a multi-line `<textarea>` (Figma `Expandable=True`).
          * @default false
         */
        "expandable": boolean;
        /**
          * Helper text below the field, linked via `aria-describedby`.
         */
        "helperText"?: string;
        /**
          * Explicit id for the control (auto-generated if omitted) to associate the label.
         */
        "inputId"?: string;
        /**
          * Visible, associated label (never use placeholder as the label).
         */
        "label": string;
        /**
          * `name` for form submission.
         */
        "name"?: string;
        /**
          * Placeholder shown when empty.
         */
        "placeholder"?: string;
        /**
          * Read-only: focusable and announced, but not editable.
          * @default false
         */
        "readonly": boolean;
        /**
          * Marks the field required (asterisk + `aria-required`; never color alone).
          * @default false
         */
        "required": boolean;
        /**
          * Contextual help shown as a tooltip affordance next to the label (Figma `Tooltip=True`).
         */
        "tooltip"?: string;
        /**
          * Message shown for the error/warning state.
         */
        "validationMessage"?: string;
        /**
          * Validation state driving error/warning visuals + ARIA.
          * @default 'none'
         */
        "validationState": NemoValidationState;
        /**
          * Current value (two-way via `nemoInput`/`nemoChange`).
          * @default ''
         */
        "value": string;
    }
}
export interface NemoButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNemoButtonElement;
}
export interface NemoTextInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNemoTextInputElement;
}
declare global {
    interface HTMLNemoButtonElementEventMap {
        "nemoClick": MouseEvent;
    }
    /**
     * Nemo button. Maps the Figma `Type` (Primary/Secondary/Tertiary/Small/Icon) and
     * `State` (Default/Hover/Disabled) onto a clean orthogonal API: variant + size are
     * props; hover/focus/pressed are CSS states.
     * Styling references the **semantic** color tier only (`--nemo-color-*`). Spacing,
     * radius, typography and elevation use the resolved Figma values directly until those
     * foundations get their own token tiers (future, additive).
     */
    interface HTMLNemoButtonElement extends Components.NemoButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNemoButtonElementEventMap>(type: K, listener: (this: HTMLNemoButtonElement, ev: NemoButtonCustomEvent<HTMLNemoButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNemoButtonElementEventMap>(type: K, listener: (this: HTMLNemoButtonElement, ev: NemoButtonCustomEvent<HTMLNemoButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNemoButtonElement: {
        prototype: HTMLNemoButtonElement;
        new (): HTMLNemoButtonElement;
    };
    /**
     * Nemo icon — renders one icon from the design system's optimized set
     * (source SVGs in `packages/components/icons/`, optimized via SVGO into the
     * generated `icons.generated.ts` registry by `npm run icons:build`).
     * Tokenized by design: every icon strokes in `currentColor`, so it inherits
     * whatever color its context already has (a button's label color, a text
     * input's icon color, plain text) — there is no per-icon color prop and no
     * hex anywhere in this component.
     * Accessibility: an icon is treated as **decorative** by default
     * (`aria-hidden="true"`) because it almost always sits next to text or
     * inside a labelled control (e.g. `nemo-button`'s `accessible-label`). Pass
     * `label` only when the icon is the *sole* accessible content — this
     * switches it to `role="img"` + `aria-label` instead.
     */
    interface HTMLNemoIconElement extends Components.NemoIcon, HTMLStencilElement {
    }
    var HTMLNemoIconElement: {
        prototype: HTMLNemoIconElement;
        new (): HTMLNemoIconElement;
    };
    interface HTMLNemoTextInputElementEventMap {
        "nemoInput": { value: string };
        "nemoChange": { value: string };
    }
    /**
     * Nemo text input. Implements the Figma text-field (node 4-33): a notched-outline
     * field with a persistent label, helper text, and error/warning validation.
     * Runtime/CSS states (Default/Hover/Active/Filled) are handled with `:hover` /
     * `:focus-within` / a populated value. Disabled, Read only, Error and Warning are props.
     * **Read-only is a distinct, focusable, announced state — never implemented as disabled.**
     * Colors reference the semantic token tier only (`--nemo-color-*`).
     */
    interface HTMLNemoTextInputElement extends Components.NemoTextInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNemoTextInputElementEventMap>(type: K, listener: (this: HTMLNemoTextInputElement, ev: NemoTextInputCustomEvent<HTMLNemoTextInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNemoTextInputElementEventMap>(type: K, listener: (this: HTMLNemoTextInputElement, ev: NemoTextInputCustomEvent<HTMLNemoTextInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNemoTextInputElement: {
        prototype: HTMLNemoTextInputElement;
        new (): HTMLNemoTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "nemo-button": HTMLNemoButtonElement;
        "nemo-icon": HTMLNemoIconElement;
        "nemo-text-input": HTMLNemoTextInputElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * Nemo button. Maps the Figma `Type` (Primary/Secondary/Tertiary/Small/Icon) and
     * `State` (Default/Hover/Disabled) onto a clean orthogonal API: variant + size are
     * props; hover/focus/pressed are CSS states.
     * Styling references the **semantic** color tier only (`--nemo-color-*`). Spacing,
     * radius, typography and elevation use the resolved Figma values directly until those
     * foundations get their own token tiers (future, additive).
     */
    interface NemoButton {
        /**
          * Accessible name — used as `aria-label`, required for icon-only buttons.
         */
        "accessibleLabel"?: string;
        /**
          * Disabled. Reflected to the host and the native button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Stretch to the full width of the container.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Icon-only button (32×32). Requires `accessibleLabel` for an accessible name.
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * Loading: shows a spinner, preserves width, sets `aria-busy`, and is non-interactive.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted on activation (not emitted while disabled or loading).
         */
        "onNemoClick"?: (event: NemoButtonCustomEvent<MouseEvent>) => void;
        /**
          * Size. `medium` ≈ 37px tall, `small` ≈ 25px tall (per Figma).
          * @default 'medium'
         */
        "size"?: NemoButtonSize;
        /**
          * Native button type.
          * @default 'button'
         */
        "type"?: NemoButtonType;
        /**
          * Visual emphasis.
          * @default 'primary'
         */
        "variant"?: NemoButtonVariant;
    }
    /**
     * Nemo icon — renders one icon from the design system's optimized set
     * (source SVGs in `packages/components/icons/`, optimized via SVGO into the
     * generated `icons.generated.ts` registry by `npm run icons:build`).
     * Tokenized by design: every icon strokes in `currentColor`, so it inherits
     * whatever color its context already has (a button's label color, a text
     * input's icon color, plain text) — there is no per-icon color prop and no
     * hex anywhere in this component.
     * Accessibility: an icon is treated as **decorative** by default
     * (`aria-hidden="true"`) because it almost always sits next to text or
     * inside a labelled control (e.g. `nemo-button`'s `accessible-label`). Pass
     * `label` only when the icon is the *sole* accessible content — this
     * switches it to `role="img"` + `aria-label` instead.
     */
    interface NemoIcon {
        /**
          * Accessible name. Omit for a decorative icon that's already described by its context (the common case — e.g. inside `nemo-button`).
         */
        "label"?: string;
        /**
          * Icon name — must match a key generated from `icons/*.svg`.
         */
        "name": NemoIconName;
        /**
          * Pixel size (square). Defaults to 24, matching every source icon's viewBox.
          * @default 24
         */
        "size"?: number;
    }
    /**
     * Nemo text input. Implements the Figma text-field (node 4-33): a notched-outline
     * field with a persistent label, helper text, and error/warning validation.
     * Runtime/CSS states (Default/Hover/Active/Filled) are handled with `:hover` /
     * `:focus-within` / a populated value. Disabled, Read only, Error and Warning are props.
     * **Read-only is a distinct, focusable, announced state — never implemented as disabled.**
     * Colors reference the semantic token tier only (`--nemo-color-*`).
     */
    interface NemoTextInput {
        /**
          * Disabled (non-focusable, non-editable). Use sparingly — prefer read-only for display.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Render a multi-line `<textarea>` (Figma `Expandable=True`).
          * @default false
         */
        "expandable"?: boolean;
        /**
          * Helper text below the field, linked via `aria-describedby`.
         */
        "helperText"?: string;
        /**
          * Explicit id for the control (auto-generated if omitted) to associate the label.
         */
        "inputId"?: string;
        /**
          * Visible, associated label (never use placeholder as the label).
         */
        "label": string;
        /**
          * `name` for form submission.
         */
        "name"?: string;
        /**
          * Emitted when the value is committed (native change).
         */
        "onNemoChange"?: (event: NemoTextInputCustomEvent<{ value: string }>) => void;
        /**
          * Emitted on every keystroke.
         */
        "onNemoInput"?: (event: NemoTextInputCustomEvent<{ value: string }>) => void;
        /**
          * Placeholder shown when empty.
         */
        "placeholder"?: string;
        /**
          * Read-only: focusable and announced, but not editable.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Marks the field required (asterisk + `aria-required`; never color alone).
          * @default false
         */
        "required"?: boolean;
        /**
          * Contextual help shown as a tooltip affordance next to the label (Figma `Tooltip=True`).
         */
        "tooltip"?: string;
        /**
          * Message shown for the error/warning state.
         */
        "validationMessage"?: string;
        /**
          * Validation state driving error/warning visuals + ARIA.
          * @default 'none'
         */
        "validationState"?: NemoValidationState;
        /**
          * Current value (two-way via `nemoInput`/`nemoChange`).
          * @default ''
         */
        "value"?: string;
    }

    interface NemoButtonAttributes {
        "variant": NemoButtonVariant;
        "size": NemoButtonSize;
        "iconOnly": boolean;
        "loading": boolean;
        "disabled": boolean;
        "type": NemoButtonType;
        "fullWidth": boolean;
        "accessibleLabel": string;
    }
    interface NemoIconAttributes {
        "name": NemoIconName;
        "size": number;
        "label": string;
    }
    interface NemoTextInputAttributes {
        "label": string;
        "value": string;
        "placeholder": string;
        "helperText": string;
        "validationState": NemoValidationState;
        "validationMessage": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "expandable": boolean;
        "tooltip": string;
        "name": string;
        "inputId": string;
    }

    interface IntrinsicElements {
        "nemo-button": Omit<NemoButton, keyof NemoButtonAttributes> & { [K in keyof NemoButton & keyof NemoButtonAttributes]?: NemoButton[K] } & { [K in keyof NemoButton & keyof NemoButtonAttributes as `attr:${K}`]?: NemoButtonAttributes[K] } & { [K in keyof NemoButton & keyof NemoButtonAttributes as `prop:${K}`]?: NemoButton[K] };
        "nemo-icon": Omit<NemoIcon, keyof NemoIconAttributes> & { [K in keyof NemoIcon & keyof NemoIconAttributes]?: NemoIcon[K] } & { [K in keyof NemoIcon & keyof NemoIconAttributes as `attr:${K}`]?: NemoIconAttributes[K] } & { [K in keyof NemoIcon & keyof NemoIconAttributes as `prop:${K}`]?: NemoIcon[K] } & OneOf<"name", NemoIcon["name"], NemoIconAttributes["name"]>;
        "nemo-text-input": Omit<NemoTextInput, keyof NemoTextInputAttributes> & { [K in keyof NemoTextInput & keyof NemoTextInputAttributes]?: NemoTextInput[K] } & { [K in keyof NemoTextInput & keyof NemoTextInputAttributes as `attr:${K}`]?: NemoTextInputAttributes[K] } & { [K in keyof NemoTextInput & keyof NemoTextInputAttributes as `prop:${K}`]?: NemoTextInput[K] } & OneOf<"label", NemoTextInput["label"], NemoTextInputAttributes["label"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Nemo button. Maps the Figma `Type` (Primary/Secondary/Tertiary/Small/Icon) and
             * `State` (Default/Hover/Disabled) onto a clean orthogonal API: variant + size are
             * props; hover/focus/pressed are CSS states.
             * Styling references the **semantic** color tier only (`--nemo-color-*`). Spacing,
             * radius, typography and elevation use the resolved Figma values directly until those
             * foundations get their own token tiers (future, additive).
             */
            "nemo-button": LocalJSX.IntrinsicElements["nemo-button"] & JSXBase.HTMLAttributes<HTMLNemoButtonElement>;
            /**
             * Nemo icon — renders one icon from the design system's optimized set
             * (source SVGs in `packages/components/icons/`, optimized via SVGO into the
             * generated `icons.generated.ts` registry by `npm run icons:build`).
             * Tokenized by design: every icon strokes in `currentColor`, so it inherits
             * whatever color its context already has (a button's label color, a text
             * input's icon color, plain text) — there is no per-icon color prop and no
             * hex anywhere in this component.
             * Accessibility: an icon is treated as **decorative** by default
             * (`aria-hidden="true"`) because it almost always sits next to text or
             * inside a labelled control (e.g. `nemo-button`'s `accessible-label`). Pass
             * `label` only when the icon is the *sole* accessible content — this
             * switches it to `role="img"` + `aria-label` instead.
             */
            "nemo-icon": LocalJSX.IntrinsicElements["nemo-icon"] & JSXBase.HTMLAttributes<HTMLNemoIconElement>;
            /**
             * Nemo text input. Implements the Figma text-field (node 4-33): a notched-outline
             * field with a persistent label, helper text, and error/warning validation.
             * Runtime/CSS states (Default/Hover/Active/Filled) are handled with `:hover` /
             * `:focus-within` / a populated value. Disabled, Read only, Error and Warning are props.
             * **Read-only is a distinct, focusable, announced state — never implemented as disabled.**
             * Colors reference the semantic token tier only (`--nemo-color-*`).
             */
            "nemo-text-input": LocalJSX.IntrinsicElements["nemo-text-input"] & JSXBase.HTMLAttributes<HTMLNemoTextInputElement>;
        }
    }
}
