/**
 * Entry point for @nemo/vue.
 *
 * `./components.ts` is generated by the `vueOutputTarget` in
 * ../components/stencil.config.ts when you run `npm run build` (or
 * `npm run build -w @nemo/components`) from the repo root. It does not exist
 * until that build has run at least once — see README.md.
 */
export * from './components';
export * from './plugin';
