import { Config } from '@stencil/core';
import { reactOutputTarget } from '@stencil/react-output-target';
import { vueOutputTarget } from '@stencil/vue-output-target';
import { angularOutputTarget } from '@stencil/angular-output-target';

// Tokens are generated by Style Dictionary into ../tokens/dist/tokens.css (the
// @nemo/tokens package, source of truth — see packages/tokens).
// Run `npm run tokens:build` (done automatically by `npm run build`) before stencil build.
export const config: Config = {
  namespace: 'nemo-ds',
  globalStyle: '../tokens/dist/tokens.css',
  outputTargets: [
    // Lazy-loaded distribution + the `loader/` entry used by consumers, Storybook,
    // and the Vue/Angular wrappers below.
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    // Standalone custom elements build (tree-shakable). Required by the React
    // output target — see https://stenciljs.com/docs/react#faqs.
    {
      type: 'dist-custom-elements',
      customElementsExportBehavior: 'auto-define-custom-elements',
      externalRuntime: false,
    },
    // Per-component generated readme.md.
    {
      type: 'docs-readme',
    },
    // Custom Elements Manifest consumed by Storybook (Phase 3) for auto prop/event docs.
    {
      type: 'docs-json',
      file: './custom-elements.json',
    },
    // Local dev server / demo page.
    {
      type: 'www',
      serviceWorker: null,
    },

    // --- Phase 4: typed framework wrappers, generated into sibling packages ---

    // React — function-component wrappers (@lit/react runtime under the hood).
    // Generates into packages/react/src/components/stencil-generated/.
    reactOutputTarget({
      outDir: '../react/src/components/stencil-generated/',
    }),

    // Vue 3 — typed wrapper components + a Vue plugin that registers the
    // lazy-loaded custom elements via the `dist` loader (defineCustomElements).
    vueOutputTarget({
      componentCorePackage: '@nemo/components',
      proxiesFile: '../vue/lib/components.ts',
    }),

    // Angular — NgModule of directive wrappers (events as RxJS Observables,
    // detached from change detection), consuming the `dist` loader via
    // APP_INITIALIZER (see packages/angular/src/lib/nemo-components.module.ts).
    angularOutputTarget({
      componentCorePackage: '@nemo/components',
      outputType: 'component',
      directivesProxyFile: '../angular/src/lib/stencil-generated/components.ts',
      directivesArrayFile: '../angular/src/lib/stencil-generated/index.ts',
    }),
  ],
};
