/**
 * Token build — DTCG (tokens/) -> Style Dictionary 4 -> generated artifacts.
 *
 * Emits (this package, @nemo/tokens):
 *   src/tokens.css   — semantic color roles as `--nemo-color-<role>`,
 *                       light under `:root`, dark under `[data-theme="dark"]`.
 *   src/tokens.ts    — typed, theme-aware var() references for components.
 *
 * `npm run build` (see package.json) runs this, then `tsc` compiles
 * src/tokens.ts -> dist/tokens.js + dist/tokens.d.ts, and copies
 * src/tokens.css -> dist/tokens.css. dist/ is what's published.
 *
 * Only the SEMANTIC tier becomes CSS variables / TS refs. Primitives are
 * build-time source material and are inlined into the semantic values.
 */
import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const THEMES = [
  { name: 'light', selector: ':root' },
  { name: 'dark', selector: '[data-theme="dark"]' },
];

// Temp build dir lives outside the project (and off any network mount) so
// Style Dictionary's intermediate files never collide or linger in the repo.
const TMP = await fs.mkdtemp(path.join(os.tmpdir(), 'nemo-sd-'));

// Semantic tokens live under the top-level `color` group; primitives under `palette`.
const isSemanticColor = (token) => token.path[0] === 'color';

// Typed map of semantic role -> CSS var reference (theme-aware, discipline-safe).
StyleDictionary.registerFormat({
  name: 'ts/nemo-semantic',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .filter(isSemanticColor)
      .map((t) => {
        const role = t.name.replace(/^nemo-color-/, '');
        return `  '${role}': 'var(--${t.name})',`;
      })
      .join('\n');
    return [
      '/**',
      ' * GENERATED by scripts/build-tokens.mjs — do not edit by hand.',
      ' * Semantic color roles as theme-aware CSS variable references.',
      ' * Components MUST consume these (never primitives, never raw hex).',
      ' */',
      'export const nemoColor = {',
      entries,
      '} as const;',
      '',
      'export type NemoColorRole = keyof typeof nemoColor;',
      '',
    ].join('\n');
  },
});

async function buildThemeCss(theme) {
  const sd = new StyleDictionary({
    source: ['tokens/primitive/**/*.json', `tokens/semantic/${theme.name}/**/*.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: 'nemo',
        buildPath: `${TMP}/`,
        files: [
          {
            destination: `tokens.${theme.name}.css`,
            format: 'css/variables',
            filter: isSemanticColor,
            options: { selector: theme.selector, outputReferences: false },
          },
        ],
      },
    },
    log: { verbosity: 'silent' },
  });
  await sd.buildAllPlatforms();
  const css = await fs.readFile(path.join(TMP, `tokens.${theme.name}.css`), 'utf8');
  // Strip Style Dictionary's per-file header; we add a single header below.
  return css.replace(/\/\*\*[\s\S]*?\*\/\n/, '').trim();
}

async function buildTs() {
  const sd = new StyleDictionary({
    source: ['tokens/primitive/**/*.json', 'tokens/semantic/light/**/*.json'],
    platforms: {
      ts: {
        transformGroup: 'css',
        prefix: 'nemo',
        buildPath: 'src/',
        files: [{ destination: 'tokens.ts', format: 'ts/nemo-semantic', filter: isSemanticColor }],
      },
    },
    log: { verbosity: 'silent' },
  });
  await sd.buildAllPlatforms();
}

async function themeExists(theme) {
  try {
    const entries = await fs.readdir(`tokens/semantic/${theme.name}`);
    return entries.some((f) => f.endsWith('.json'));
  } catch {
    return false;
  }
}

async function main() {
  await fs.mkdir('src', { recursive: true });

  const blocks = ['/* GENERATED by scripts/build-tokens.mjs — do not edit by hand. */'];
  for (const theme of THEMES) {
    if (!(await themeExists(theme))) {
      console.warn(`! skipping "${theme.name}" — no tokens in tokens/semantic/${theme.name}/`);
      continue;
    }
    blocks.push(await buildThemeCss(theme));
  }
  await fs.writeFile('src/tokens.css', blocks.join('\n\n') + '\n');

  await buildTs();

  await fs.rm(TMP, { recursive: true, force: true }).catch(() => {});
  console.log('✓ src/tokens.css + tokens.ts generated');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
