/**
 * Entry point for @nemo/react.
 *
 * `components/stencil-generated/` is generated by the `reactOutputTarget` in
 * ../components/stencil.config.ts when you run `npm run build` (or
 * `npm run build -w @nemo/components`) from the repo root. It does not exist
 * until that build has run at least once — see README.md.
 */
export * from './components/stencil-generated';
