#!/usr/bin/env node
/**
 * Icon pipeline (Phase 6) — optimizes every source SVG in icons/ with SVGO and
 * emits a generated registry consumed by the `nemo-icon` component.
 *
 * Source SVGs (icons/*.svg) each own their shape data only; the consistent
 * stroke/fill/currentColor treatment and the size are owned by `nemo-icon`
 * itself (src/components/icon/icon.tsx), so icons inherit button/input
 * theming instead of hard-coding color per icon.
 *
 * Run via `npm run icons:build` (also runs automatically before `stencil
 * build` — see package.json).
 */
import { optimize } from 'svgo';
import { promises as fs } from 'node:fs';
import path from 'node:path';

const SRC_DIR = 'icons';
const OUT_FILE = 'src/components/icon/icons.generated.ts';

const NAME_RE = /^[a-z][a-z0-9-]*$/;

async function main() {
  const files = (await fs.readdir(SRC_DIR)).filter((f) => f.endsWith('.svg')).sort();

  if (files.length === 0) {
    throw new Error(`No .svg files found in ${SRC_DIR}/`);
  }

  const entries = [];
  for (const file of files) {
    const name = path.basename(file, '.svg');
    if (!NAME_RE.test(name)) {
      throw new Error(
        `Invalid icon name "${name}" (${file}) — icon names must be lowercase kebab-case.`,
      );
    }

    const raw = await fs.readFile(path.join(SRC_DIR, file), 'utf8');
    const { data: optimized } = optimize(raw, {
      plugins: ['preset-default'],
    });

    // Keep only the inner markup (the shape data) — the outer <svg> wrapper,
    // including viewBox/currentColor/size, is owned by nemo-icon itself.
    const inner = optimized
      .replace(/^<svg[^>]*>/, '')
      .replace(/<\/svg>\s*$/, '')
      .trim();

    if (!inner) {
      throw new Error(`${file} optimized down to empty markup — check the source SVG.`);
    }

    entries.push(`  '${name}': ${JSON.stringify(inner)},`);
  }

  const out = [
    '/**',
    ' * GENERATED by scripts/build-icons.mjs — do not edit by hand.',
    ' * SVGO-optimized icon shape markup, keyed by name. Consumed by',
    ' * <nemo-icon name="..."> (icon.tsx), which owns the <svg> wrapper',
    ' * (viewBox, currentColor, size) so every icon inherits theming.',
    ' * Source SVGs live in packages/components/icons/.',
    ' */',
    'export const nemoIcons = {',
    entries.join('\n'),
    '} as const;',
    '',
    'export type NemoIconName = keyof typeof nemoIcons;',
    '',
  ].join('\n');

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, out);
  console.log(`✓ ${files.length} icon(s) optimized -> ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
